name: expense_track
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.20.1
  flutter_slidable: ^3.1.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:

  uses-material-design: true