name: expense_track
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.20.1
  flutter_slidable: ^4.0.0
  fl_chart: ^0.70.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  assets:
    - assets/splash_icon.png
    - assets/app_icon.png
  uses-material-design: true

flutter_native_splash:
  color: "#F5F5DC"
  image: assets/splash_icon.png
  android_12:
    image: assets/splash_icon.png
    color: "#F5F5DC"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # Path to your square app icon
  adaptive_icon_background: "#F5F5DC"  # Background color for the adaptive icon
  adaptive_icon_foreground: "assets/app_icon.png"  # Square image as the foreground
  remove_alpha_ios: true  # Remove alpha channel for iOS to avoid issues in the App Store
